import Link from "next/link"
import { ArrowUpRight, Check } from "lucide-react"
import { Reveal } from "@/components/cinematic/reveal"

const skills = ["Graphic Design & Illustration", "Adobe Illustrator", "Adobe Photoshop", "Adobe InDesign", "Motion Graphics & Video Editing", "Adobe After Effects", "Adobe Premiere Pro", "Visual & Brand Design", "Packaging Design", "Marketing Creatives", "Social Media Visuals", "Photography", "Sketching & Layout Design"]

export default function AboutPage() {
  return <main className="px-4 pb-24 pt-32 md:px-6 md:pt-40"><div className="mx-auto max-w-7xl"><Reveal><p className="text-xs font-semibold uppercase tracking-[0.3em] text-gold">About</p><h1 className="mt-4 max-w-5xl font-heading text-5xl font-semibold tracking-tight md:text-7xl">Creative thinking, practical design, polished execution.</h1></Reveal><div className="mt-16 grid gap-12 lg:grid-cols-[1.1fr_.9fr]"><Reveal><p className="text-lg leading-8 text-muted-foreground">I’m Saad Ullah Khan, a creative graphic designer with 5+ years of experience across marketing creatives, packaging, social media visuals, print materials, branding, digital assets, and illustration.</p><p className="mt-6 text-base leading-8 text-muted-foreground">My work has supported food, real estate, healthcare, retail, and other business-focused environments. I focus on clear visual communication and designs that are ready for real production—not just concepts.</p><Link href="/#work" className="mt-8 inline-flex items-center gap-2 rounded-full bg-gradient-to-r from-gold to-orange px-5 py-3 text-sm font-semibold text-primary-foreground">Explore experience <ArrowUpRight className="h-4 w-4" /></Link></Reveal><Reveal delay={.1}><div className="glass-strong rounded-[28px] p-7"><p className="text-xs uppercase tracking-[0.25em] text-gold">Core skills</p><div className="mt-6 space-y-3">{skills.map(skill=><div key={skill} className="flex items-center gap-3 text-sm"><span className="flex h-6 w-6 items-center justify-center rounded-full bg-gold/10 text-gold"><Check className="h-3.5 w-3.5"/></span>{skill}</div>)}</div></div></Reveal></div></div></main>
}
