// Auto-generated by scripts/scan-portfolio.mjs.
// Do not edit manually.

export const portfolio = [
  {
    "slug": "branding-and-corporate-design",
    "name": "Branding & Corporate Design",
    "role": "Selected Work",
    "description": "Logos, corporate visuals, brand assets, and consistent visual identity applications.",
    "categories": [
      {
        "slug": "selected-work",
        "name": "Selected Work",
        "items": [
          {
            "src": "/portfolio/Branding & Corporate Design/2.jpg",
            "title": "2",
            "type": "image"
          },
          {
            "src": "/portfolio/Branding & Corporate Design/6.jpg",
            "title": "6",
            "type": "image"
          },
          {
            "src": "/portfolio/Branding & Corporate Design/7.jpg",
            "title": "7",
            "type": "image"
          },
          {
            "src": "/portfolio/Branding & Corporate Design/bDEAL 2.jpg",
            "title": "bDEAL 2",
            "type": "image"
          },
          {
            "src": "/portfolio/Branding & Corporate Design/buger hut-PNG m.jpg",
            "title": "buger hut PNG m",
            "type": "image"
          },
          {
            "src": "/portfolio/Branding & Corporate Design/-DANA-DUNKA.jpg",
            "title": "DANA DUNKA",
            "type": "image"
          },
          {
            "src": "/portfolio/Branding & Corporate Design/File Name Lost (10).png",
            "title": "File Name Lost (10)",
            "type": "image"
          },
          {
            "src": "/portfolio/Branding & Corporate Design/File Name Lost (114).jpg",
            "title": "File Name Lost (114)",
            "type": "image"
          },
          {
            "src": "/portfolio/Branding & Corporate Design/File Name Lost (1467).jpg",
            "title": "File Name Lost (1467)",
            "type": "image"
          },
          {
            "src": "/portfolio/Branding & Corporate Design/File Name Lost (1631).jpg",
            "title": "File Name Lost (1631)",
            "type": "image"
          },
          {
            "src": "/portfolio/Branding & Corporate Design/File Name Lost (2886).jpg",
            "title": "File Name Lost (2886)",
            "type": "image"
          },
          {
            "src": "/portfolio/Branding & Corporate Design/File Name Lost (2926).jpg",
            "title": "File Name Lost (2926)",
            "type": "image"
          },
          {
            "src": "/portfolio/Branding & Corporate Design/File Name Lost (46).jpg",
            "title": "File Name Lost (46)",
            "type": "image"
          },
          {
            "src": "/portfolio/Branding & Corporate Design/maxi logo black.jpg",
            "title": "maxi logo black",
            "type": "image"
          },
          {
            "src": "/portfolio/Branding & Corporate Design/Untitled-1LOGO-01.jpg",
            "title": "Untitled 1LOGO 01",
            "type": "image"
          }
        ]
      }
    ],
    "itemCount": 15,
    "featured": "/portfolio/Branding & Corporate Design/2.jpg"
  },
  {
    "slug": "catalogue-and-product-design",
    "name": "Catalogue & Product Design",
    "role": "Selected Work",
    "description": "Product catalogues, product layouts, product presentation, and commercial visual communication.",
    "categories": [
      {
        "slug": "selected-work",
        "name": "Selected Work",
        "items": [
          {
            "src": "/portfolio/Catalogue & Product Design/400+ product flyer.pdf",
            "title": "400+ product flyer",
            "type": "pdf"
          },
          {
            "src": "/portfolio/Catalogue & Product Design/catalogue BCD.pdf",
            "title": "catalogue BCD",
            "type": "pdf"
          },
          {
            "src": "/portfolio/Catalogue & Product Design/CELLAIRIS Catalogue_22-SEP-25 copy.pdf",
            "title": "CELLAIRIS Catalogue 22 SEP 25 copy",
            "type": "pdf"
          },
          {
            "src": "/portfolio/Catalogue & Product Design/chocolate.pdf",
            "title": "chocolate",
            "type": "pdf"
          },
          {
            "src": "/portfolio/Catalogue & Product Design/crisp catalogue.pdf",
            "title": "crisp catalogue",
            "type": "pdf"
          },
          {
            "src": "/portfolio/Catalogue & Product Design/Final Corporate Diary .pdf",
            "title": "Final Corporate Diary",
            "type": "pdf"
          },
          {
            "src": "/portfolio/Catalogue & Product Design/pfg pak catlogue2.pdf",
            "title": "pfg pak catlogue2",
            "type": "pdf"
          },
          {
            "src": "/portfolio/Catalogue & Product Design/sweets.pdf",
            "title": "sweets",
            "type": "pdf"
          }
        ]
      }
    ],
    "itemCount": 8,
    "featured": null
  },
  {
    "slug": "illustration-and-sketching",
    "name": "Illustration & Sketching",
    "role": "Selected Work",
    "description": "Hand-drawn sketches, portraits, illustrations, and selected artwork.",
    "categories": [
      {
        "slug": "selected-work",
        "name": "Selected Work",
        "items": [
          {
            "src": "/portfolio/Illustration & Sketching/Canon EOS 6D3.JPG",
            "title": "Canon EOS 6D3",
            "type": "image"
          },
          {
            "src": "/portfolio/Illustration & Sketching/File Name Lost (112).jpg",
            "title": "File Name Lost (112)",
            "type": "image"
          },
          {
            "src": "/portfolio/Illustration & Sketching/File Name Lost (115).png",
            "title": "File Name Lost (115)",
            "type": "image"
          },
          {
            "src": "/portfolio/Illustration & Sketching/File Name Lost (119).jpg",
            "title": "File Name Lost (119)",
            "type": "image"
          },
          {
            "src": "/portfolio/Illustration & Sketching/File Name Lost (124).jpg",
            "title": "File Name Lost (124)",
            "type": "image"
          },
          {
            "src": "/portfolio/Illustration & Sketching/File Name Lost (1345).jpg",
            "title": "File Name Lost (1345)",
            "type": "image"
          },
          {
            "src": "/portfolio/Illustration & Sketching/File Name Lost (1346).jpg",
            "title": "File Name Lost (1346)",
            "type": "image"
          },
          {
            "src": "/portfolio/Illustration & Sketching/File Name Lost (1360).jpg",
            "title": "File Name Lost (1360)",
            "type": "image"
          },
          {
            "src": "/portfolio/Illustration & Sketching/File Name Lost (1601).jpg",
            "title": "File Name Lost (1601)",
            "type": "image"
          },
          {
            "src": "/portfolio/Illustration & Sketching/File Name Lost (1649).jpg",
            "title": "File Name Lost (1649)",
            "type": "image"
          },
          {
            "src": "/portfolio/Illustration & Sketching/File Name Lost (1686).jpg",
            "title": "File Name Lost (1686)",
            "type": "image"
          },
          {
            "src": "/portfolio/Illustration & Sketching/File Name Lost (1779).jpg",
            "title": "File Name Lost (1779)",
            "type": "image"
          },
          {
            "src": "/portfolio/Illustration & Sketching/File Name Lost (282).jpg",
            "title": "File Name Lost (282)",
            "type": "image"
          },
          {
            "src": "/portfolio/Illustration & Sketching/File Name Lost (53).png",
            "title": "File Name Lost (53)",
            "type": "image"
          },
          {
            "src": "/portfolio/Illustration & Sketching/File Name Lost (57).png",
            "title": "File Name Lost (57)",
            "type": "image"
          },
          {
            "src": "/portfolio/Illustration & Sketching/File Name Lost (7).jpg",
            "title": "File Name Lost (7)",
            "type": "image"
          }
        ]
      }
    ],
    "itemCount": 16,
    "featured": "/portfolio/Illustration & Sketching/Canon EOS 6D3.JPG"
  },
  {
    "slug": "large-format-and-outdoor",
    "name": "Large Format & Outdoor",
    "role": "Selected Work",
    "description": "Vehicle wraps, banners, hoardings, signage, retail displays, and large-format advertising.",
    "categories": [
      {
        "slug": "selected-work",
        "name": "Selected Work",
        "items": [
          {
            "src": "/portfolio/Large Format & Outdoor/banner-mokeup.jpg",
            "title": "banner mokeup",
            "type": "image"
          },
          {
            "src": "/portfolio/Large Format & Outdoor/DJI_0332.jpg",
            "title": "DJI 0332",
            "type": "image"
          },
          {
            "src": "/portfolio/Large Format & Outdoor/DJI_0333 copy.jpg",
            "title": "DJI 0333 copy",
            "type": "image"
          },
          {
            "src": "/portfolio/Large Format & Outdoor/FINAL.jpg",
            "title": "FINAL",
            "type": "image"
          },
          {
            "src": "/portfolio/Large Format & Outdoor/lorry-standing-outdoors-near-warehouse.jpg",
            "title": "lorry standing outdoors near warehouse",
            "type": "image"
          },
          {
            "src": "/portfolio/Large Format & Outdoor/mokeup-truck.jpg",
            "title": "mokeup truck",
            "type": "image"
          },
          {
            "src": "/portfolio/Large Format & Outdoor/vinyl-dooe-mokeup.jpg",
            "title": "vinyl dooe mokeup",
            "type": "image"
          }
        ]
      }
    ],
    "itemCount": 7,
    "featured": "/portfolio/Large Format & Outdoor/banner-mokeup.jpg"
  },
  {
    "slug": "packaging",
    "name": "Packaging",
    "role": "Selected Work",
    "description": "Product packaging, boxes, labels, packaging layouts, and retail-ready visual design.",
    "categories": [
      {
        "slug": "selected-work",
        "name": "Selected Work",
        "items": [
          {
            "src": "/portfolio/Packaging/02_package_box_02_45.jpg",
            "title": "02 package box 02 45",
            "type": "image"
          },
          {
            "src": "/portfolio/Packaging/100W-pd-C-C-Grey.jpg",
            "title": "100W pd C C Grey",
            "type": "image"
          },
          {
            "src": "/portfolio/Packaging/3D BOX_NUVIA C_MASTER-20-OCT-25 copy.jpg",
            "title": "3D BOX NUVIA C MASTER 20 OCT 25 copy",
            "type": "image"
          },
          {
            "src": "/portfolio/Packaging/3D-BOX_NUVIA-S_20-OCT-25.png",
            "title": "3D BOX NUVIA S 20 OCT 25",
            "type": "image"
          },
          {
            "src": "/portfolio/Packaging/3D-BOX_ROYCE-L_OCT-25.png",
            "title": "3D BOX ROYCE L OCT 25",
            "type": "image"
          },
          {
            "src": "/portfolio/Packaging/3d-front-back.jpg",
            "title": "3d front back",
            "type": "image"
          },
          {
            "src": "/portfolio/Packaging/766-2 logoinfo-01.jpg",
            "title": "766 2 logoinfo 01",
            "type": "image"
          },
          {
            "src": "/portfolio/Packaging/back.png",
            "title": "back",
            "type": "image"
          },
          {
            "src": "/portfolio/Packaging/Back.jpg",
            "title": "Back",
            "type": "image"
          },
          {
            "src": "/portfolio/Packaging/Back (2).jpg",
            "title": "Back (2)",
            "type": "image"
          },
          {
            "src": "/portfolio/Packaging/Back (2).png",
            "title": "Back (2)",
            "type": "image"
          },
          {
            "src": "/portfolio/Packaging/back (3).png",
            "title": "back (3)",
            "type": "image"
          },
          {
            "src": "/portfolio/Packaging/Back (3).jpg",
            "title": "Back (3)",
            "type": "image"
          },
          {
            "src": "/portfolio/Packaging/back-ivory.png",
            "title": "back ivory",
            "type": "image"
          },
          {
            "src": "/portfolio/Packaging/File Name Lost (1282).jpg",
            "title": "File Name Lost (1282)",
            "type": "image"
          },
          {
            "src": "/portfolio/Packaging/File Name Lost (1283).jpg",
            "title": "File Name Lost (1283)",
            "type": "image"
          },
          {
            "src": "/portfolio/Packaging/File Name Lost (1288).jpg",
            "title": "File Name Lost (1288)",
            "type": "image"
          },
          {
            "src": "/portfolio/Packaging/front.png",
            "title": "front",
            "type": "image"
          },
          {
            "src": "/portfolio/Packaging/Front.jpg",
            "title": "Front",
            "type": "image"
          },
          {
            "src": "/portfolio/Packaging/Front (2).jpg",
            "title": "Front (2)",
            "type": "image"
          },
          {
            "src": "/portfolio/Packaging/Front (2).png",
            "title": "Front (2)",
            "type": "image"
          },
          {
            "src": "/portfolio/Packaging/front (3).png",
            "title": "front (3)",
            "type": "image"
          },
          {
            "src": "/portfolio/Packaging/front-back.png",
            "title": "front back",
            "type": "image"
          },
          {
            "src": "/portfolio/Packaging/Front Back.png",
            "title": "Front Back",
            "type": "image"
          },
          {
            "src": "/portfolio/Packaging/front-ivory.png",
            "title": "front ivory",
            "type": "image"
          },
          {
            "src": "/portfolio/Packaging/HARMO Wireless Headphones - Ivory_PRINT_26-MARCH-2026-01.jpg",
            "title": "HARMO Wireless Headphones Ivory PRINT 26 MARCH 2026 01",
            "type": "image"
          },
          {
            "src": "/portfolio/Packaging/Image_20260323064107_1223_62.jpg",
            "title": "Image 20260323064107 1223 62",
            "type": "image"
          },
          {
            "src": "/portfolio/Packaging/Image_20260323064108_1225_62.jpg",
            "title": "Image 20260323064108 1225 62",
            "type": "image"
          },
          {
            "src": "/portfolio/Packaging/life-style.png",
            "title": "life style",
            "type": "image"
          },
          {
            "src": "/portfolio/Packaging/life-style-Model-a.png",
            "title": "life style Model a",
            "type": "image"
          },
          {
            "src": "/portfolio/Packaging/M-EPHRUSHL2WH.jpg",
            "title": "M EPHRUSHL2WH",
            "type": "image"
          },
          {
            "src": "/portfolio/Packaging/master_.jpg",
            "title": "master",
            "type": "image"
          },
          {
            "src": "/portfolio/Packaging/NUVIA C Calling Smart Watch-Rose Gold_PRINT_11-AUG-25-01.jpg",
            "title": "NUVIA C Calling Smart Watch Rose Gold PRINT 11 AUG 25 01",
            "type": "image"
          },
          {
            "src": "/portfolio/Packaging/NUVIA C_PRINT_24-SEP-25-01.jpg",
            "title": "NUVIA C PRINT 24 SEP 25 01",
            "type": "image"
          },
          {
            "src": "/portfolio/Packaging/NUVIA C_PRINT_24-SEP-25-02.jpg",
            "title": "NUVIA C PRINT 24 SEP 25 02",
            "type": "image"
          },
          {
            "src": "/portfolio/Packaging/NUVIA C_UM_ENGLISH_PRINT-01.jpg",
            "title": "NUVIA C UM ENGLISH PRINT 01",
            "type": "image"
          },
          {
            "src": "/portfolio/Packaging/NUVIA S_PRINT_24-SEP-25-01.jpg",
            "title": "NUVIA S PRINT 24 SEP 25 01",
            "type": "image"
          },
          {
            "src": "/portfolio/Packaging/NUVIA S_PRINT_24-SEP-25-02.jpg",
            "title": "NUVIA S PRINT 24 SEP 25 02",
            "type": "image"
          },
          {
            "src": "/portfolio/Packaging/NUVIA S_UM_TURKISH_PRINT-01.jpg",
            "title": "NUVIA S UM TURKISH PRINT 01",
            "type": "image"
          },
          {
            "src": "/portfolio/Packaging/Premium Wall Charger Foldable 35W A+C - Black_PRINT_21-NOV-2025-01.jpg",
            "title": "Premium Wall Charger Foldable 35W A+C Black PRINT 21 NOV 2025 01",
            "type": "image"
          },
          {
            "src": "/portfolio/Packaging/Premium WTA PD 45W Logo & Info Print_print_18-JUL-25-01.jpg",
            "title": "Premium WTA PD 45W Logo & Info Print print 18 JUL 25 01",
            "type": "image"
          },
          {
            "src": "/portfolio/Packaging/Quad_Brochure_Mockup_2.png",
            "title": "Quad Brochure Mockup 2",
            "type": "image"
          },
          {
            "src": "/portfolio/Packaging/ROYCE L Smart Watch BT Calling-Dark Gray_PRINT_11-AUG-25-01.jpg",
            "title": "ROYCE L Smart Watch BT Calling Dark Gray PRINT 11 AUG 25 01",
            "type": "image"
          },
          {
            "src": "/portfolio/Packaging/RUSH L2 Lightning Wired Earphones - White_ Print 14-jul-2025-01.jpg",
            "title": "RUSH L2 Lightning Wired Earphones White Print 14 jul 2025 01",
            "type": "image"
          },
          {
            "src": "/portfolio/Packaging/SPIRAL CABLE USB C - USB C PD 60W 2M - Black_PRINT_08-DEC-2025-01.jpg",
            "title": "SPIRAL CABLE USB C USB C PD 60W 2M Black PRINT 08 DEC 2025 01",
            "type": "image"
          },
          {
            "src": "/portfolio/Packaging/SPIRAL CABLE USB C - USB C PD 60W 2M - Black_PRINT_08-DEC-2025-02.jpg",
            "title": "SPIRAL CABLE USB C USB C PD 60W 2M Black PRINT 08 DEC 2025 02",
            "type": "image"
          },
          {
            "src": "/portfolio/Packaging/USB C Hub Multiports 4in1 _PRINT_ Silver_27-JAN-2026-01.jpg",
            "title": "USB C Hub Multiports 4in1 PRINT Silver 27 JAN 2026 01",
            "type": "image"
          },
          {
            "src": "/portfolio/Packaging/USB C Hub Multiports 4in1 _PRINT_ Silver_27-JAN-2026-02.jpg",
            "title": "USB C Hub Multiports 4in1 PRINT Silver 27 JAN 2026 02",
            "type": "image"
          },
          {
            "src": "/portfolio/Packaging/USB C Hub Multiports 4in1 -UM_PRINT_ Silver_27-JAN-2026-01.jpg",
            "title": "USB C Hub Multiports 4in1 UM PRINT Silver 27 JAN 2026 01",
            "type": "image"
          },
          {
            "src": "/portfolio/Packaging/USB C Hub Multiports 4in1 -UM_PRINT_ Silver_27-JAN-2026-02.jpg",
            "title": "USB C Hub Multiports 4in1 UM PRINT Silver 27 JAN 2026 02",
            "type": "image"
          },
          {
            "src": "/portfolio/Packaging/USB C Hub Multiports 8in1 - Silver_Logoinfo_PRINT_16-DEC-2025-01.jpg",
            "title": "USB C Hub Multiports 8in1 Silver Logoinfo PRINT 16 DEC 2025 01",
            "type": "image"
          },
          {
            "src": "/portfolio/Packaging/USB C Hub Multiports 8in1 - Silver_PRINT_27-JAN-2026-01.jpg",
            "title": "USB C Hub Multiports 8in1 Silver PRINT 27 JAN 2026 01",
            "type": "image"
          },
          {
            "src": "/portfolio/Packaging/USB C Hub Multiports 8in1 - Silver_PRINT_27-JAN-2026-02.jpg",
            "title": "USB C Hub Multiports 8in1 Silver PRINT 27 JAN 2026 02",
            "type": "image"
          },
          {
            "src": "/portfolio/Packaging/USB C Hub Multiports 8in1 - Silver_UM_PRINT_27-JAN-2026-01.jpg",
            "title": "USB C Hub Multiports 8in1 Silver UM PRINT 27 JAN 2026 01",
            "type": "image"
          },
          {
            "src": "/portfolio/Packaging/USB C Hub Multiports 8in1 - Silver_UM_PRINT_27-JAN-2026-02.jpg",
            "title": "USB C Hub Multiports 8in1 Silver UM PRINT 27 JAN 2026 02",
            "type": "image"
          }
        ]
      }
    ],
    "itemCount": 55,
    "featured": "/portfolio/Packaging/02_package_box_02_45.jpg"
  },
  {
    "slug": "print-and-promotional",
    "name": "Print & Promotional",
    "role": "Selected Work",
    "description": "Flyers, brochures, menus, posters, promotional materials, and print-focused communication design.",
    "categories": [
      {
        "slug": "selected-work",
        "name": "Selected Work",
        "items": [
          {
            "src": "/portfolio/Print & Promotional/01 (1).jpg",
            "title": "01 (1)",
            "type": "image"
          },
          {
            "src": "/portfolio/Print & Promotional/01 (2).jpg",
            "title": "01 (2)",
            "type": "image"
          },
          {
            "src": "/portfolio/Print & Promotional/02 (2).jpg",
            "title": "02 (2)",
            "type": "image"
          },
          {
            "src": "/portfolio/Print & Promotional/03 (1).jpg",
            "title": "03 (1)",
            "type": "image"
          },
          {
            "src": "/portfolio/Print & Promotional/03 (2).jpg",
            "title": "03 (2)",
            "type": "image"
          },
          {
            "src": "/portfolio/Print & Promotional/04 (4).jpg",
            "title": "04 (4)",
            "type": "image"
          },
          {
            "src": "/portfolio/Print & Promotional/appitzer.jpg",
            "title": "appitzer",
            "type": "image"
          },
          {
            "src": "/portfolio/Print & Promotional/appitzer-pfg.jpg",
            "title": "appitzer pfg",
            "type": "image"
          },
          {
            "src": "/portfolio/Print & Promotional/Banner-1-–-Bakery.jpg",
            "title": "Banner 1 – Bakery",
            "type": "image"
          },
          {
            "src": "/portfolio/Print & Promotional/Banner-2-–-Country-Garden-.jpg",
            "title": "Banner 2 – Country Garden",
            "type": "image"
          },
          {
            "src": "/portfolio/Print & Promotional/burger-fw.jpg",
            "title": "burger fw",
            "type": "image"
          },
          {
            "src": "/portfolio/Print & Promotional/burger-recipe-pg2-fw.jpg",
            "title": "burger recipe pg2 fw",
            "type": "image"
          },
          {
            "src": "/portfolio/Print & Promotional/Chicken Flyer.jpg",
            "title": "Chicken Flyer",
            "type": "image"
          },
          {
            "src": "/portfolio/Print & Promotional/chicken flyer1.jpg",
            "title": "chicken flyer1",
            "type": "image"
          },
          {
            "src": "/portfolio/Print & Promotional/cubboard-flyer.jpg",
            "title": "cubboard flyer",
            "type": "image"
          },
          {
            "src": "/portfolio/Print & Promotional/daily fresh Informational flyer .jpg",
            "title": "daily fresh Informational flyer",
            "type": "image"
          },
          {
            "src": "/portfolio/Print & Promotional/Dairy, Cheeze & Chilled.jpg",
            "title": "Dairy, Cheeze & Chilled",
            "type": "image"
          },
          {
            "src": "/portfolio/Print & Promotional/derby offer (2).jpg",
            "title": "derby offer (2)",
            "type": "image"
          },
          {
            "src": "/portfolio/Print & Promotional/DF-Vegetable-Flyer-pg-1.jpg",
            "title": "DF Vegetable Flyer pg 1",
            "type": "image"
          },
          {
            "src": "/portfolio/Print & Promotional/DF-Vegetable-Flyer-pg-2.jpg",
            "title": "DF Vegetable Flyer pg 2",
            "type": "image"
          },
          {
            "src": "/portfolio/Print & Promotional/dinaclass-product006.jpg",
            "title": "dinaclass product006",
            "type": "image"
          },
          {
            "src": "/portfolio/Print & Promotional/Email-footer-Signature.jpg",
            "title": "Email footer Signature",
            "type": "image"
          },
          {
            "src": "/portfolio/Print & Promotional/fb & linkedin@2x-100.jpg",
            "title": "fb & linkedin@2x 100",
            "type": "image"
          },
          {
            "src": "/portfolio/Print & Promotional/fcc002-east-end-range.jpg",
            "title": "fcc002 east end range",
            "type": "image"
          },
          {
            "src": "/portfolio/Print & Promotional/fccbann001.jpg",
            "title": "fccbann001",
            "type": "image"
          },
          {
            "src": "/portfolio/Print & Promotional/File Name Lost (117).jpg",
            "title": "File Name Lost (117)",
            "type": "image"
          },
          {
            "src": "/portfolio/Print & Promotional/File Name Lost (1268).jpg",
            "title": "File Name Lost (1268)",
            "type": "image"
          },
          {
            "src": "/portfolio/Print & Promotional/File Name Lost (18).jpg",
            "title": "File Name Lost (18)",
            "type": "image"
          },
          {
            "src": "/portfolio/Print & Promotional/File Name Lost (63).jpg",
            "title": "File Name Lost (63)",
            "type": "image"
          },
          {
            "src": "/portfolio/Print & Promotional/food cupboard banner.jpg",
            "title": "food cupboard banner",
            "type": "image"
          },
          {
            "src": "/portfolio/Print & Promotional/frozen flyer (1).jpg",
            "title": "frozen flyer (1)",
            "type": "image"
          },
          {
            "src": "/portfolio/Print & Promotional/frozen flyer (10).jpg",
            "title": "frozen flyer (10)",
            "type": "image"
          },
          {
            "src": "/portfolio/Print & Promotional/frozen flyer (11).jpg",
            "title": "frozen flyer (11)",
            "type": "image"
          },
          {
            "src": "/portfolio/Print & Promotional/frozen flyer (12).jpg",
            "title": "frozen flyer (12)",
            "type": "image"
          },
          {
            "src": "/portfolio/Print & Promotional/frozen flyer (13).jpg",
            "title": "frozen flyer (13)",
            "type": "image"
          },
          {
            "src": "/portfolio/Print & Promotional/frozen flyer (14).jpg",
            "title": "frozen flyer (14)",
            "type": "image"
          },
          {
            "src": "/portfolio/Print & Promotional/frozen flyer (15).jpg",
            "title": "frozen flyer (15)",
            "type": "image"
          },
          {
            "src": "/portfolio/Print & Promotional/frozen flyer (16).jpg",
            "title": "frozen flyer (16)",
            "type": "image"
          },
          {
            "src": "/portfolio/Print & Promotional/frozen flyer (17).jpg",
            "title": "frozen flyer (17)",
            "type": "image"
          },
          {
            "src": "/portfolio/Print & Promotional/frozen flyer (18).jpg",
            "title": "frozen flyer (18)",
            "type": "image"
          },
          {
            "src": "/portfolio/Print & Promotional/frozen flyer (19).jpg",
            "title": "frozen flyer (19)",
            "type": "image"
          },
          {
            "src": "/portfolio/Print & Promotional/Jumma offer (1).jpg",
            "title": "Jumma offer (1)",
            "type": "image"
          },
          {
            "src": "/portfolio/Print & Promotional/Jumma offer (2).jpg",
            "title": "Jumma offer (2)",
            "type": "image"
          },
          {
            "src": "/portfolio/Print & Promotional/new product chocolate cake.jpg",
            "title": "new product chocolate cake",
            "type": "image"
          },
          {
            "src": "/portfolio/Print & Promotional/offer (2).jpg",
            "title": "offer (2)",
            "type": "image"
          },
          {
            "src": "/portfolio/Print & Promotional/offer-01 (1).jpg",
            "title": "offer 01 (1)",
            "type": "image"
          },
          {
            "src": "/portfolio/Print & Promotional/offer-01 (2).jpg",
            "title": "offer 01 (2)",
            "type": "image"
          },
          {
            "src": "/portfolio/Print & Promotional/offer-01 (3).jpg",
            "title": "offer 01 (3)",
            "type": "image"
          },
          {
            "src": "/portfolio/Print & Promotional/peri-peri-wings.jpg",
            "title": "peri peri wings",
            "type": "image"
          },
          {
            "src": "/portfolio/Print & Promotional/peri-peri-wings-2.jpg",
            "title": "peri peri wings 2",
            "type": "image"
          },
          {
            "src": "/portfolio/Print & Promotional/PFG Driver flyer BDM .jpg",
            "title": "PFG Driver flyer BDM",
            "type": "image"
          },
          {
            "src": "/portfolio/Print & Promotional/PFG lambweston.jpg",
            "title": "PFG lambweston",
            "type": "image"
          },
          {
            "src": "/portfolio/Print & Promotional/pfg wholesale (1).jpg",
            "title": "pfg wholesale (1)",
            "type": "image"
          },
          {
            "src": "/portfolio/Print & Promotional/pfg wholesale (2).jpg",
            "title": "pfg wholesale (2)",
            "type": "image"
          },
          {
            "src": "/portfolio/Print & Promotional/pfg wholesale (3).jpg",
            "title": "pfg wholesale (3)",
            "type": "image"
          },
          {
            "src": "/portfolio/Print & Promotional/pfg wholesale (4).jpg",
            "title": "pfg wholesale (4)",
            "type": "image"
          },
          {
            "src": "/portfolio/Print & Promotional/pizza-day-fw-.jpg",
            "title": "pizza day fw",
            "type": "image"
          },
          {
            "src": "/portfolio/Print & Promotional/pizza-day-fw2-.jpg",
            "title": "pizza day fw2",
            "type": "image"
          },
          {
            "src": "/portfolio/Print & Promotional/QW offer-011 (2).jpg",
            "title": "QW offer 011 (2)",
            "type": "image"
          },
          {
            "src": "/portfolio/Print & Promotional/QW offer-011 (3).jpg",
            "title": "QW offer 011 (3)",
            "type": "image"
          },
          {
            "src": "/portfolio/Print & Promotional/qw sweet flyer (2).jpg",
            "title": "qw sweet flyer (2)",
            "type": "image"
          },
          {
            "src": "/portfolio/Print & Promotional/qw sweet flyer (3).jpg",
            "title": "qw sweet flyer (3)",
            "type": "image"
          },
          {
            "src": "/portfolio/Print & Promotional/saving calculator dialogue box.jpg",
            "title": "saving calculator dialogue box",
            "type": "image"
          },
          {
            "src": "/portfolio/Print & Promotional/smash-burger-banner.jpg",
            "title": "smash burger banner",
            "type": "image"
          },
          {
            "src": "/portfolio/Print & Promotional/soft drink offer (2).jpg",
            "title": "soft drink offer (2)",
            "type": "image"
          },
          {
            "src": "/portfolio/Print & Promotional/Special-Offer-flyer.jpg",
            "title": "Special Offer flyer",
            "type": "image"
          },
          {
            "src": "/portfolio/Print & Promotional/Untitled-1 copy.jpg",
            "title": "Untitled 1 copy",
            "type": "image"
          },
          {
            "src": "/portfolio/Print & Promotional/Untitled-1-Recovered.png",
            "title": "Untitled 1 Recovered",
            "type": "image"
          },
          {
            "src": "/portfolio/Print & Promotional/WhatsApp Image 2023-01-04 at 03.16.43.jpeg",
            "title": "WhatsApp Image 2023 01 04 at 03.16.43",
            "type": "image"
          }
        ]
      }
    ],
    "itemCount": 69,
    "featured": "/portfolio/Print & Promotional/01 (1).jpg"
  },
  {
    "slug": "social-media-and-digital",
    "name": "Social Media & Digital",
    "role": "Selected Work",
    "description": "Social media campaigns, promotional creatives, digital marketing visuals, and web graphics.",
    "categories": [
      {
        "slug": "selected-work",
        "name": "Selected Work",
        "items": [
          {
            "src": "/portfolio/Social Media & Digital/06 (1).jpg",
            "title": "06 (1)",
            "type": "image"
          },
          {
            "src": "/portfolio/Social Media & Digital/06 (4).jpg",
            "title": "06 (4)",
            "type": "image"
          },
          {
            "src": "/portfolio/Social Media & Digital/1.jpg",
            "title": "1",
            "type": "image"
          },
          {
            "src": "/portfolio/Social Media & Digital/10X10 (2).png",
            "title": "10X10 (2)",
            "type": "image"
          },
          {
            "src": "/portfolio/Social Media & Digital/2.jpg",
            "title": "2",
            "type": "image"
          },
          {
            "src": "/portfolio/Social Media & Digital/278582235_1384885948618299_2063624676882979746_n.jpg",
            "title": "278582235 1384885948618299 2063624676882979746 n",
            "type": "image"
          },
          {
            "src": "/portfolio/Social Media & Digital/278619672_1386184738488420_3541249969907700071_n.jpg",
            "title": "278619672 1386184738488420 3541249969907700071 n",
            "type": "image"
          },
          {
            "src": "/portfolio/Social Media & Digital/3.jpg",
            "title": "3",
            "type": "image"
          },
          {
            "src": "/portfolio/Social Media & Digital/314808069_172807995403286_8975462480389599667_n.jpg",
            "title": "314808069 172807995403286 8975462480389599667 n",
            "type": "image"
          },
          {
            "src": "/portfolio/Social Media & Digital/4.jpg",
            "title": "4",
            "type": "image"
          },
          {
            "src": "/portfolio/Social Media & Digital/5.jpg",
            "title": "5",
            "type": "image"
          },
          {
            "src": "/portfolio/Social Media & Digital/860b3b4bc4b2e85b9faeff1ab49d8b35-Recovered.jpg",
            "title": "860b3b4bc4b2e85b9faeff1ab49d8b35 Recovered",
            "type": "image"
          },
          {
            "src": "/portfolio/Social Media & Digital/constructio.jpg",
            "title": "constructio",
            "type": "image"
          },
          {
            "src": "/portfolio/Social Media & Digital/drinks-2.jpg",
            "title": "drinks 2",
            "type": "image"
          },
          {
            "src": "/portfolio/Social Media & Digital/Exclusive offer .jpg",
            "title": "Exclusive offer",
            "type": "image"
          },
          {
            "src": "/portfolio/Social Media & Digital/fcc-halloween-brand-post.jpg",
            "title": "fcc halloween brand post",
            "type": "image"
          },
          {
            "src": "/portfolio/Social Media & Digital/File Name Lost (1420).jpg",
            "title": "File Name Lost (1420)",
            "type": "image"
          },
          {
            "src": "/portfolio/Social Media & Digital/File Name Lost (3002).jpg",
            "title": "File Name Lost (3002)",
            "type": "image"
          },
          {
            "src": "/portfolio/Social Media & Digital/File Name Lost (865).jpg",
            "title": "File Name Lost (865)",
            "type": "image"
          },
          {
            "src": "/portfolio/Social Media & Digital/File Name Lost (866).jpg",
            "title": "File Name Lost (866)",
            "type": "image"
          },
          {
            "src": "/portfolio/Social Media & Digital/File Name Lost (868).jpg",
            "title": "File Name Lost (868)",
            "type": "image"
          },
          {
            "src": "/portfolio/Social Media & Digital/Front.jpg",
            "title": "Front",
            "type": "image"
          },
          {
            "src": "/portfolio/Social Media & Digital/frozen-chicken.jpg",
            "title": "frozen chicken",
            "type": "image"
          },
          {
            "src": "/portfolio/Social Media & Digital/HOUSE-FOR-RENT-SLECT-URDU.jpg",
            "title": "HOUSE FOR RENT SLECT URDU",
            "type": "image"
          },
          {
            "src": "/portfolio/Social Media & Digital/LOCATION MAP CAPITAL VALLEY maxiple.jpg",
            "title": "LOCATION MAP CAPITAL VALLEY maxiple",
            "type": "image"
          },
          {
            "src": "/portfolio/Social Media & Digital/maxi new rates 01 KANAL (2).jpg",
            "title": "maxi new rates 01 KANAL (2)",
            "type": "image"
          },
          {
            "src": "/portfolio/Social Media & Digital/metro city comming soon - Copy.jpg",
            "title": "metro city comming soon Copy",
            "type": "image"
          },
          {
            "src": "/portfolio/Social Media & Digital/NUVIA-C3.jpg",
            "title": "NUVIA C3",
            "type": "image"
          },
          {
            "src": "/portfolio/Social Media & Digital/NUVIA-S.jpg",
            "title": "NUVIA S",
            "type": "image"
          },
          {
            "src": "/portfolio/Social Media & Digital/NUVIA-S_4.jpg",
            "title": "NUVIA S 4",
            "type": "image"
          },
          {
            "src": "/portfolio/Social Media & Digital/oil-poster.jpg",
            "title": "oil poster",
            "type": "image"
          },
          {
            "src": "/portfolio/Social Media & Digital/okm maxiple with no.jpg",
            "title": "okm maxiple with no",
            "type": "image"
          },
          {
            "src": "/portfolio/Social Media & Digital/open-file.jpg",
            "title": "open file",
            "type": "image"
          },
          {
            "src": "/portfolio/Social Media & Digital/orange-drink.jpg",
            "title": "orange drink",
            "type": "image"
          },
          {
            "src": "/portfolio/Social Media & Digital/over-seas-discount-new-metro-city (2).jpg",
            "title": "over seas discount new metro city (2)",
            "type": "image"
          },
          {
            "src": "/portfolio/Social Media & Digital/pfg-halloween-brand-post.jpg",
            "title": "pfg halloween brand post",
            "type": "image"
          },
          {
            "src": "/portfolio/Social Media & Digital/pfg-pizza-day.jpg",
            "title": "pfg pizza day",
            "type": "image"
          },
          {
            "src": "/portfolio/Social Media & Digital/Premium-Nylon-3in1-Cable_Poster_08-Sept-25.jpg",
            "title": "Premium Nylon 3in1 Cable Poster 08 Sept 25",
            "type": "image"
          },
          {
            "src": "/portfolio/Social Media & Digital/quaside-drinks.jpg",
            "title": "quaside drinks",
            "type": "image"
          },
          {
            "src": "/portfolio/Social Media & Digital/QW carousel (3).jpg",
            "title": "QW carousel (3)",
            "type": "image"
          },
          {
            "src": "/portfolio/Social Media & Digital/QW carousel (4).jpg",
            "title": "QW carousel (4)",
            "type": "image"
          },
          {
            "src": "/portfolio/Social Media & Digital/QW carousel (5).jpg",
            "title": "QW carousel (5)",
            "type": "image"
          },
          {
            "src": "/portfolio/Social Media & Digital/QW carousel (6).jpg",
            "title": "QW carousel (6)",
            "type": "image"
          },
          {
            "src": "/portfolio/Social Media & Digital/rice-poster.jpg",
            "title": "rice poster",
            "type": "image"
          },
          {
            "src": "/portfolio/Social Media & Digital/rice poster copy.jpg",
            "title": "rice poster copy",
            "type": "image"
          },
          {
            "src": "/portfolio/Social Media & Digital/royce-2_C.jpg",
            "title": "royce 2 C",
            "type": "image"
          },
          {
            "src": "/portfolio/Social Media & Digital/ROYCE-L.jpg",
            "title": "ROYCE L",
            "type": "image"
          },
          {
            "src": "/portfolio/Social Media & Digital/sauce.jpg",
            "title": "sauce",
            "type": "image"
          },
          {
            "src": "/portfolio/Social Media & Digital/sauces-post (2).jpg",
            "title": "sauces post (2)",
            "type": "image"
          },
          {
            "src": "/portfolio/Social Media & Digital/seerat construction 2.jpg",
            "title": "seerat construction 2",
            "type": "image"
          },
          {
            "src": "/portfolio/Social Media & Digital/sialkot-feaures-aqua-2.jpg",
            "title": "sialkot feaures aqua 2",
            "type": "image"
          },
          {
            "src": "/portfolio/Social Media & Digital/sialkot-post.jpg",
            "title": "sialkot post",
            "type": "image"
          },
          {
            "src": "/portfolio/Social Media & Digital/SOLD OUT MAXIPLE FILE NEW 2.jpg",
            "title": "SOLD OUT MAXIPLE FILE NEW 2",
            "type": "image"
          },
          {
            "src": "/portfolio/Social Media & Digital/special-offer-2 (2).jpg",
            "title": "special offer 2 (2)",
            "type": "image"
          },
          {
            "src": "/portfolio/Social Media & Digital/tips-for-chef-pfg.jpg",
            "title": "tips for chef pfg",
            "type": "image"
          },
          {
            "src": "/portfolio/Social Media & Digital/top-product-sausage-post.jpg",
            "title": "top product sausage post",
            "type": "image"
          },
          {
            "src": "/portfolio/Social Media & Digital/Travel-adapter-65W_21-nov-2025.jpg",
            "title": "Travel adapter 65W 21 nov 2025",
            "type": "image"
          },
          {
            "src": "/portfolio/Social Media & Digital/Ultima-C_Social-Poster_10-Dec-2025.jpg",
            "title": "Ultima C Social Poster 10 Dec 2025",
            "type": "image"
          },
          {
            "src": "/portfolio/Social Media & Digital/ULTIMA-PRO-Social-Poster_10-DEC-2025.jpg",
            "title": "ULTIMA PRO Social Poster 10 DEC 2025",
            "type": "image"
          },
          {
            "src": "/portfolio/Social Media & Digital/Venue MAXIPLE FINAL.jpg",
            "title": "Venue MAXIPLE FINAL",
            "type": "image"
          }
        ]
      }
    ],
    "itemCount": 60,
    "featured": "/portfolio/Social Media & Digital/06 (1).jpg"
  }
] as const
